"""Public interface for the CUMCM prediction and evaluation toolkit."""

from .core import (
    BacktestProtocol,
    Calibration,
    DriftFeature,
    DriftReport,
    FoldRecord,
    KnownLimitation,
    ModelSpec,
    OOFResult,
    PredictConfig,
    PredictResult,
    PredictionDataset,
    PredictionToolkitError,
    RankPerturbation,
    StabilityReport,
    TemporalLeakageError,
    TemporalMetadataError,
    TuningLeakageError,
    backtest,
    calibrate,
    drift_diagnostic,
    fit_predict,
    rank_stability,
)

__all__ = [
    "BacktestProtocol",
    "Calibration",
    "DriftFeature",
    "DriftReport",
    "FoldRecord",
    "KnownLimitation",
    "ModelSpec",
    "OOFResult",
    "PredictConfig",
    "PredictResult",
    "PredictionDataset",
    "PredictionToolkitError",
    "RankPerturbation",
    "StabilityReport",
    "TemporalLeakageError",
    "TemporalMetadataError",
    "TuningLeakageError",
    "backtest",
    "calibrate",
    "drift_diagnostic",
    "fit_predict",
    "rank_stability",
]
